apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oidc.secret.yaml
  - app-user.secret.yaml
  - forgejo.secret.yaml
  - cnpg.cluster.yaml

helmCharts:
  - name: valkey
    releaseName: forgejo-cache
    repo: https:// valkey.io/valkey-helm/
    version: 0.9.3
    valuesFile: valkey.values.yaml
    namespace: forgejo

  - name: forgejo
    releaseName: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: 16.0.0
    valuesFile: forgejo.values.yaml
    namespace: forgejo
