apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-ingress-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-cedille-production-v2
  destination:
    server: https://cedille.kubernetes.omni.siderolabs.io?cluster=k8s-cedille-shared
    namespace: vault
  source:
    repoURL: https://github.com/ClubCedille/k8s-shared
    path: apps/vault
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
